---
title: "Seism"
author: "Pamela"
date: "11/10/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
 
```{r setup, include=FALSE}
#install.packages("PerformanceAnalytics")
#install.packages("GGally")
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
library(readxl)
library(psych)
library(dplyr)
library(MASS)
library(corrplot)
library(ggplot2)
library(reshape)
library(PerformanceAnalytics)
library(GGally)
#p_new <- read_excel("prueba ppn-250920.xlsx", skip = 1)
p_new <- read.csv("pruebappn.csv", encoding="UTF-8")

```

## Descriptive data

```{r desc}
p_new$Daño <- factor(p_new$Daño)
p_new$Daño <- ordered(p_new$Daño, levels = c("sin daño","pandeo leve","pandeo","colapso"))
p_new$Daño_n <- as.numeric(p_new$Daño)

table(p_new$Daño)
describe(p_new)
summary(p_new)

p_new_to_use <- dplyr::select(p_new, Cr_r, G, Dm, HLLm, tmm, Mag, Daño_n)
#chart.Correlation(p_new_to_use)
#ggpairs(p_new, columns = c("Cr_r", "G", "Dm", "HLLm", "tmm", "Mag", "Daño")) 
#ggpairs(p_new, columns = c("Cr_r", "G", "Dm", "HLLm", "tmm", "Mag", "Daño"), 
#       ggplot2::aes(colour=Daño))

#ggplot(p_new, aes(x = Cr_r, fill = Daño)) +
#  geom_density() +
#  facet_grid(~ Daño) +
#  theme(legend.position="bottom")

#ggplot(p_new, aes(x = (tmm^2/(HLLm^2*Dm*G)), y = Cr_r, color = factor(Mag), size = factor(Mag))) +
#  geom_point() +
#  facet_grid(~ Daño) +
#  theme(legend.position="bottom")



#ggplot(p_new, aes(x = HLLm, y = Dm)) +
#  geom_point() 

```

## Modelling

```{r model}
#options(contrasts = c("contr.treatment", "contr.poly"))
#reg_pl1 <- polr(Daño ~ HLLm + tmm + G + Dm + Mag, data = p_new, Hess = TRUE) 
#summary(reg_pl1)
#(ci <- confint(reg_pl1))

#4 cat
#reg_pl <- polr(Daño ~ tmm + I(1/HLLm) + Dm*HLLm + G*tmm + Dm*HLLm*G*tmm, data = p_new, Hess = TRUE) 
#summary(reg_pl)
#round(ci <- confint(reg_pl),3)

#round(exp(cbind(OR = coef(reg_pl), ci)),3)

#p_new <- cbind(p_new, predicted = predict(reg_pl, p_new))
#table(p_new$Daño,p_new$predicted)

#newdat <- cbind(p_new[,c("Cr_r", "HLLm", "Dm", "G", "tmm", "Daño", "Mag")], 
#                predict(reg_pl, p_new, type = "probs"))
#lnewdatProb <- melt(newdat, id.vars = c("Cr_r","HLLm", "Dm", "tmm", "Daño", "Mag"), 
#                    variable_name = "Prediction")

#ggplot(na.omit(lnewdatProb[,c("HLLm","value","Daño","Prediction")]), 
#       aes(x =  HLLm, y = value, 
#           color = factor(ifelse(round(value,2) >= 0.49 & 
#                                   as.numeric(Prediction) == as.numeric(Daño),1,0)))) +
#  geom_point() +
#  facet_grid(Prediction ~ Daño, labeller =  label_bquote("Prediction"==.(Prediction))) +
#  theme(legend.position="bottom") +
#  labs(title = "Predictions\n", y = "Probabilities", color = "Good predictions >= 0.49\n") +
#  scale_color_manual(labels = c("No", "Yes"), values = c("blue","darkgreen"))

#pandeo leve hacia arriba
#mglm2 <- glm(I(as.numeric(Daño) >= 2) ~ HLLm*Dm + Dm*tmm, family="binomial", data = p_new)
#summary(mglm2)

#pandeo  hacia arriba
#mglm3 <- glm(I(as.numeric(Daño) >= 3) ~ HLLm*Dm + Dm*tmm, family="binomial", data = p_new)
#summary(mglm3)

#Colapso 
#mglm4 <- glm(I(as.numeric(Daño) > 3) ~ HLLm*Dm + Dm*tmm, family="binomial", data = p_new)
#summary(mglm4)

#newdata3 <- cbind(p_new, predict(mglm2, newdata = p_new, type = "link",
#                                    se = TRUE))
#newdata3 <- within(newdata3, {
#  PredictedProb <- plogis(fit)
#  LL <- plogis(fit - (1.96 * se.fit))
#  UL <- plogis(fit + (1.96 * se.fit))
#})

#ggplot(newdata3, aes(x = Mag, y = PredictedProb)) + 
#  geom_ribbon(aes(ymin = LL, ymax = UL, fill = Daño), alpha = 0.2) + 
#  geom_line(aes(colour = Daño), size = 1)

```

## Simulation

tmm : Espesor de la capa inferior del manto (cm)
Hmm : Altura del contenido del estanque (m)
Dm  : Diámetro del estanque (m)
G   : Peso especifico del contenido (tonf/cm3)



```{r sim, echo=FALSE}
#Excel formula
#p_new$Cr_st = 15.4*10^6*(p_new$tmm*0.03937) / ((p_new$HLLm*3.281)^2 * (p_new$Dm*3.281) * (p_new$G*62.428)) # as stated in excel file

#Picture formula
#p_new$Cr_st = 950 * (p_new$tmm^2) / (p_new$HLLm^2 * p_new$Dm * p_new$G)

#Cr <- function(t,H,D,G) {
#  round((950 * (t^2)) / ((H)^2 * (D) * (G)),3)
#}

#Sim <- tibble(R_t = runif(100, min(p_new$t, na.rm = TRUE), max(p_new$t, na.rm = TRUE)),
#              R_H = runif(100, min(p_new$Hft, na.rm = TRUE), max(p_new$Hft, na.rm = TRUE)),
#              R_D = runif(100, min(p_new$Dft, na.rm = TRUE), max(p_new$Dft, na.rm = TRUE)),
#              R_G = runif(100, min(p_new$G, na.rm = TRUE), max(p_new$G, na.rm = TRUE))) %>% 
#  mutate(cr = Cr(t = R_t, H = R_H, D = R_D, G = R_G)) %>% 
#  arrange(cr)
#describe(Sim)


#variable1 <- "R_D"

library(gghighlight)
#i = 5
#t_x <- Sim$R_t[i]
#H_x <- Sim$R_H[i]
#D_x <- Sim$R_D[i]
#G_x <- Sim$R_G[i]

#Sim  %>% 
#  ggplot(aes_string(x = variable1, y = "cr")) +
#  geom_point() +
#  geom_point(aes(x = D_x, y = Cr(t = t_x, H = H_x, D = D_x, G = G_x)), size = 5) +
#  theme(legend.position = "none") +
#  labs(title = "Resistencia del estanque", x = "Diametro del estanque (m)", y =  "Coeficiente de resistencia - Cr") +
#  geom_label(aes(x = D_x, y = Cr(t = t_x, H = H_x, D = D_x, G = G_x), 
#                 label = paste("t = ", round(t_x,2), "H = ", round(H_x,2), "D = ", round(D_x,2), "G = ", round(G_x,2))),
#               hjust = 0, vjust = -1, fill = "orange", colour = "darkblue", alpha= 0.5)

```

